[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  colorscheme iceberg 
  hi NormalFloat guifg=#BBECFD guibg=#095F4B
'''

[[plugins]]
repo = 'Shougo/deoppet.nvim'
hook_add = '''
  source ~/.config/nvim/plugin_settings/deoppet.vim
'''

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add='''
  source ~/.config/nvim/plugin_settings/deol.vim
'''

[[plugins]]
repo = 'kana/vim-metarw'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.config/nvim/plugin_settings/lightline.vim
'''

[[plugins]]
repo = 'thosakwe/vim-flutter'

[[plugins]]
repo = 'emonkak/vim-metarw-gist'
