[[plugins]]
repo = 'sakhnik/nvim-gdb'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  source ~/.config/nvim/plugin_settings/ale.vim
'''

[[plugins]]
repo = 'tyru/notify-changed.vim'

[[plugins]]
repo = 'mattn/vim-sonictemplate'
hook_source='''
let g:sonictemplate_vim_template_dir = [
      \ '$NVIM/sonictemplate'
      \]
'''
