[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
hook_add = '''
  source ~/.config/nvim/plugin_settings/coc.vim
'''

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  source ~/.config/nvim/plugin_settings/ale.vim
'''
