[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
    highlight clear ALEError
    highlight clear ALEWarning
    let g:ale_lint_on_enter = 0
    let g:ale_sign_column_always = 1
    let g:ale_set_loclist = 0
    let g:ale_set_quickfix = 1
    
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
              source $NVIM/denite.vim
              '''

[[plugins]]
repo = 'Shougo/deoppet.nvim'


[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add='''
let g:deol#shell_history_path = '~/.zsh_history'
nnoremap <C-d>t :Deol -split=floating
'''

[[plugins]]
repo = 'kana/vim-metarw'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
              source $NVIM/lightline.vim
              '''

[[plugins]]
repo = 'emonkak/vim-metarw-gist'
